name: Server Jar

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Branch, tag or commit to build
        required: true
        default: feat/village-raids

jobs:
  build:
    name: Build powernukkitx.jar
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1
          submodules: false

      - uses: actions/setup-java@v6.0.1
        with:
          distribution: temurin
          java-version: 25

      - uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - run: chmod +x gradlew

      - run: ./gradlew shadowJar --no-daemon --parallel --max-workers=2 --stacktrace

      - uses: actions/upload-artifact@v7
        with:
          name: powernukkitx-${{ github.run_number }}
          path: build/powernukkitx.jar
          if-no-files-found: error
